#include <cstdlib>

namespace Common {
    constexpr size_t LOG_QUEUE_SIZE = 8 * 1024 * 1024; // num chars in logger queue
    constexpr size_t ME_MAX_TICKERS = 8; // max number of instruments listed
    constexpr size_t ME_MAX_CLIENT_UPDATES = 256 * 1024; // max number of unprocessed order requests
    constexpr size_t ME_MAX_MARKET_UPDATES = 256 * 1024; // max number of updates generated by matching engine to publish
    constexpr size_t ME_MAX_NUM_CLIENTS = 256; // max number of participants allowed
    constexpr size_t ME_MAX_ORDER_IDs; // max number of orders possible for a single instrument
    constexpr size_t ME_MAX_PRICE_LEVELS; // max depth of price levels for the order book 
}